Simple Calculator/Models/Calculator.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Simple_Calculator.Models
{
    public class Calculator
    {
        [Required(ErrorMessage ="Please enter first Number")]
        [RegularExpression(@"^-?\d+(\.\d+)?$", ErrorMessage ="Please enter a valid Numeric for Number1")]
        public string Number1 { get; set; }

        [Required(ErrorMessage ="Please enter second Number")]
        [RegularExpression(@"^-?\d+(\.\d+)?$", ErrorMessage = "Please enter a valid Numeric for Number2")]//The [RegularExpression] attribute ensures that the input is a valid numeric value. It matches positive, negative, and decimal numbers.
        public string Number2 { get; set; }

        [Required(ErrorMessage = "Please select an operaion")]
        public string Operation { get; set; }
        public double? Result { get; set; }

        public double? GetParsedNumber1()
        {
            return double.TryParse(Number1, out double num1) ? num1 : (double?)null;
        }

        public double? GetParsedNumber2()
        {
            return double.TryParse(Number2, out double num2) ? num2 : (double?)null;
        }


    }
}

Simple Calculator/Controllers/CalculateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Simple_Calculator.Models;

namespace Simple_Calculator.Controllers
{
    public class CalculateController : Controller
    {
        // GET: Calculate
        public ActionResult Index()
        {
            return View(new Calculator());//The purpose of passing new CalculatorModel() to the view is to provide the view with a strongly-typed model instance that: Enables binding of input fields to model properties.

        }
        [HttpPost]

        public ActionResult Index(Calculator calculator_obj)
        {
            double? num1 = null; // Declare num1 and num2 outside
            double? num2 = null;

            if (ModelState.IsValid)
            {
                num1 = calculator_obj.GetParsedNumber1();
                num2 = calculator_obj.GetParsedNumber2();

            }
            if(num1 == null || num2 == null)
            {
                if (num1 == null)
                {
                    ModelState.AddModelError("Number1", "Please enter a valid numeric value for Number 1.");
                }if (num2 == null)
                {
                    ModelState.AddModelError("Number2", "Please enter a valid numeric value for Number 1.");
                }
            }
            // Perform the calculation
            switch (calculator_obj.Operation)
            {
                case "Add":
                    calculator_obj.Result = num1 + num2;
                    break;
                case "Subtract":
                    calculator_obj.Result = num1 - num2;
                    break;
                case "Multiply":
                    calculator_obj.Result = num1 * num2;
                    break;
                case "Divide":
                    if (num2 != 0)
                        calculator_obj.Result = num1 / num2;
                    else
                        ModelState.AddModelError("Number2", "Division by zero is not allowed.");
                    break;
                default:
                    ModelState.AddModelError("Operation", "Invalid operation.");
                    break;
            }
            return View(calculator_obj);
        }

    }
}

Simple Calculator/Views/Calculate/Index.cshtml
@model Simple_Calculator.Models.Calculator
@*Model class imported now we can accessing it properties by objects*@

@{
    ViewBag.Title = "Calculator";
}

<h1>ICalculator</h1>

@using (Html.BeginForm("Index", "Calculate", FormMethod.Post))
{
    <div>
        @Html.TextBoxFor(m => m.Number1, new { @class = "form-control", placeholder = "Enter First Number" })
        @Html.ValidationMessageFor(m => m.Number1)
    </div>
    <div>
        @Html.TextBoxFor(m => m.Number2, new { @class = "form-control", placeholder = "Enter Second Number" })
        @Html.ValidationMessageFor(m => m.Number2)
    </div>
    <div>
        @Html.DropDownListFor(m => m.Operation,
            new SelectList(new[] { "Add", "Subtract", "Multiply", "Divide" }, "Operation"),
            new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Operation)
    </div>
    <div>
        <input type="submit" value="Calculate" class="btn btn-primary" />
    </div>
}
@if (Model.Result != null)
{
    <div>
        <h3>Result: @Model.Result</h3>
    </div>
}

Simple Calculator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>*@

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>